server:
  port: 8081

spring:
  application:
    name: service-provider # 应用名称，注册到eureka后的服务名称
  datasource:
    url: jdbc:mysql://localhost:3306/students?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    # 不加此配置driver-class-name，会报错Failed to configure a DataSource: no embedded datasource could be configured
    #    1、JDBC连接Mysql5 com.mysql.jdbc.Driver:
    #    2、JDBC连接Mysql6 com.mysql.cj.jdbc.Driver， 需要指定时区serverTimezone:
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.liuhedev.service.pojo

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    #    默认情况下每个30秒服务会向注册中心发送一次心跳，证明自己还活着。如果超过90秒没有发送心跳，EurekaServer就会认为该服务宕机，会从服务列表中移除，这两个值在生产环境不要修改，默认即可。
    #    服务失效时间，默认值90秒
    lease-expiration-duration-in-seconds: 10 # 10秒即过期
    #    服务续约(renew)的间隔
    lease-renewal-interval-in-seconds: 5 # 5秒一次心跳